project_id = "whnugsalualaacsnxmcn"

[functions.create-admin]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.verify-email-code]
verify_jwt = false

[functions.send-plan-notification]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false
